services:
  - type: web
    name: aeroflux-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
